import requests
import os

BOT_TOKEN = os.getenv("BOT_TOKEN")
WEBHOOK_URL = os.getenv("WEBHOOK_URL")

url = f"https://api.telegram.org/bot{BOT_TOKEN}/setWebhook"
data = {"url": WEBHOOK_URL}

requests.post(url, data=data)
